export const programmingCards = [
  {
    id: 13,
    image: "https://i.ibb.co/k0yrzNz/Boxing-Training.png",
    title: "MVP Boxing Training",
    description: "Unity",
    url: "https://sidequestvr.com/app/29430/training-box-vr",
  },
  {
    id: 12,
    image: "https://i.ibb.co/1M5vc5Q/dental-Products.png",
    title: "MVP Dental Products",
    description: "Figma",
    url: "https://www.figma.com/design/8XoA8tRA9YzA9fxIPA5wym/Dental_Products-(Copy)?node-id=907%3A12765&t=sVEwbSPVfAGQ4hXs-1",
  },
  {
    id: 11,
    image: "https://i.ibb.co/3Sp7RBJ/password-Generator.jpg",
    title: "Password Generator",
    description: "Tailwind, React, js",
    url: "https://jdrcabrera123.github.io/passwordGenerator/",
  },
  {
    id: 9,
    image: "https://i.ibb.co/cJPmXdV/p9-01.png",
    title: "Job searcher",
    description: "html, sass, React, js",
    url: "https://jdrcabrera123.github.io/jobPortal/",
  },
  {
    id: 8,
    image: "https://i.ibb.co/GFtdBVF/p8-01.png",
    title: "Ecommerce",
    description: "html, sass, js",
    url: "https://jdrcabrera123.github.io/testEcommerce/",
  },
  {
    id: 1,
    image: "https://i.ibb.co/2dWytWh/12.png",
    title: "Clothing site",
    description: "html, sass, js",
    url: "https://jdrcabrera123.github.io/sitesix/#",
  },
  {
    image: "https://i.ibb.co/1sMdTKb/shoot-Them-All.png",
    id: 2,
    title: "Shoot Them All",
    description: "C#, Unity, PC version",
    url: "https://sharemygame.com/@TheCowow/shoot-them-all",
  },
  {
    image: "https://i.ibb.co/sPS3XMr/Bladesh.png",
    id: 3,
    title: "Bladesh",
    description: "C#, Unity, PC, mobile version",
    url: "https://sharemygame.com/@TheCowow/bladesh",
  },
  {
    image: "https://i.ibb.co/Lt7ps7p/Alfredito.png",
    id: 4,
    title: "Saving Alfredito",
    description: "C#, Unity, mobile version",
    url: "https://simmer.io/@TheCowow/saving-alfredito",
  },
  {
    image: "https://i.ibb.co/564Jk8f/Icon-1.png",
    id: 5,
    title: "Bob the Box",
    description: "C#, Unity, PC, mobile version",
    url: "https://simmer.io/@TheCowow/bob-the-box",
  },
  {
    image: "https://i.ibb.co/jMQy5KY/Asset-23.png",
    id: 6,
    title: "Ultra ping - Super pong",
    description: "C#, Unity, PC, mobile version",
    url: "https://simmer.io/@TheCowow/ultra-ping-super-pong",
  },
  {
    image: "https://i.ibb.co/JtJTxFc/Asset-35.png",
    id: 7,
    title: "Menu test",
    description: "C#, Unity, PC, mobile version",
    url: "https://simmer.io/@TheCowow/jay-the-game",
  },
  {
    image: "https://i.ibb.co/BfKV86Y/123.png",
    id: 10,
    title: "Movies",
    description: "html, sass, js, React",
    url: "https://jdrcabrera123.github.io/movies/",
  },
];
